---
- name: Create electron configuration directory
  file: path={{ home_dir }}/{{ config_dir }}
        state=directory

- name: Create recording directory
  file: path={{ home_dir }}/{{ config_dir }}/{{ recording_dir }}
        state=directory

- name: Clone Stitcher Repo
  git: repo={{ stitcher_url }} dest={{ home_dir }}/{{ stitcher_dir }}

- name: Download stitcher script
  get_url:
    url={{ script_url }}
    dest={{ home_dir }}/{{ stitcher_dir }}/{{ script }}

- name: Give executable permissions to script
  file: path={{ home_dir }}/{{ stitcher_dir }}/{{ script }}
        state=file
        mode="u+rwx"
