---
- hosts: 127.0.0.1
  connection: local
  vars:
    home_dir: "{{ ansible_env.HOME }}"
  roles:
    - {role: kbrebanov.pip, tags: ['pip']}
    - {role: stitcher, tags: ['stitcher']}
    - {role: ffmpeg, tags: ['ffmpeg']}
    - {role: opencv, tags: ['opencv']}
