---
- name: Install dependencies
  become: true
  apt: "name='{{ item }}' state=installed update_cache=yes"
  with_items:
    - build-essential
    - cmake
    - libgtk2.0-dev
    - pkg-config
    - ffmpeg
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - python-dev
    - python-numpy
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev
    - v4l2ucp
    - v4l-utils
    - libv4l-dev

- name: Download latest OpenCV
  get_url:
    url='{{ opencv_src_url }}'
    dest='{{ opencv_src_file }}'

- name: Unzip OpenCV
  unarchive:
    src='{{ opencv_src_file }}'
    dest='{{ opencv_src_dir }}'

- name: Create Build Directory
  file: "path='{{ opencv_src_dir }}/{{ opencv_src_build_dir }}' state=directory recurse=false"

- name: Run CMake
  command: "cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_PYTHON_SUPPORT=ON -D BUILD_EXAMPLES=ON .."
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"

- name: Build OpenCV from src
  command: make
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"

- name: Install OpenCV
  command: "make install"
  become: true
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"
