---
- name: Install dependencies
  become: true
  apt: "name='{{ item }}' state=installed update_cache=yes"
  with_items:
    - build-essential
    - cmake
    - libgtk2.0-dev
    - pkg-config
    - ffmpeg
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - python-dev
    - python-numpy
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev

- get_url: "url='{{ opencv_src_url }}' dest='{{ opencv_src_file }}'"
- command: "unzip -n {{ opencv_src_file }}"
- file: "path='{{ opencv_src_dir }}/{{ opencv_src_build_dir }}' state=directory recurse=false"
- command: "cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_PYTHON_SUPPORT=ON -D BUILD_EXAMPLES=ON .."
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"
- command: make
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"
- command: "make install"
  become: true
  args:
    chdir: "{{ opencv_src_dir }}/{{ opencv_src_build_dir }}"
