---
opencv_src_url: "https://github.com/opencv/opencv/archive/3.1.0.zip"
opencv_src_file: "~/opencv-3.1.0.zip"
opencv_src_dir: "~/opencv-3.1.0"
opencv_src_build_dir: "build"
opencv_contrib_url: "https://github.com/opencv/opencv_contrib/archive/3.1.0.zip"
opencv_contrib_src: "~/opencv_contrib-3.1.0.zip"
opencv_contrib_dir: "~/opencv_contrib-3.1.0"
